### ISSUE TITLE
Setup information re dependencies

### ISSUE THREAD

**Issue by dorchard** [Cambridge-ICCS/Summer-School-Julia-Tutorial#1]
There are a lot of packages here which will need to be installed first I think:
```
	using LinearAlgebra
	using StaticArrays
	using SymPy
	using Plots
	using Images
	using PlutoUI
	using Symbolics
	using BenchmarkTools
	using PartialFunctions
	using OffsetArrays
	using ForwardDiff
	using OrdinaryDiffEq
	using Statistics
	using Markdown
```
What's the best way for pulling in all these dependencies automatically? 

Perhaps you can start populating README.md to include this kind of info.

**Comment by casterkay** [comment]
`Pluto.jl` will automatically install these packages. But I will write a tutorial on how to install Julia and Pluto.jl in the first place.

**Comment by dorchard** [comment]
Ah okay - for some reason the first time I tried it I had package issues but seems okay now.
