### ISSUE TITLE
Questions about the tutorial

### ISSUE THREAD

**Issue by casterkay** [Cambridge-ICCS/Summer-School-Julia-Tutorial#3]
## A few Pluto questions:
- Is there a way to run one cell at a time via the keyboard?
Yes, by pressing `Shift+Enter`
- Is there a way to get the results to display after the code cells rather than before? I guess if not just warn / remind people at the start that it's different to the usual Jupyter style of results after.
No. We should mention this in the presentation.
- How do you get Greek unicode characters? The example showing binding variables locally uses theta but typing \theta doesn't give it to me like it does in other editors.
You need to press `tab` after you enter `\theta`. We should also mention this in the lecture.

## Basics
- First section: the last example probably needs a bit of explanation.
OK.
- Is it worth putting more 'text' cells in, esp. around places like this?
Yes I also think we need to put more text cells for explanation of the code.
- Types and Fields section:
   - fieldtypes(typeof(z)), z.re, getfield(z, :im) should probably be broken up rather than doing a triple so that you can explain it bit by bit?
   OK.
   - Do we need the Dict(zip(...)) construction? Could add some unnecessary complication if you just want to show the field names and types for T which could be done each separately?
   But it also introduces the usage of `Dict`, and the result looks nicer as it's one-to-one mapping from field name to field type.
- Arrays section:
  - I wasn't so sure about mixing StepRanges with Vectors. Why put these together here?
  Because I think they are very similar, sharing lots of methods in common.
- the examples will require explaining higher order functions. Are we expecting people will be familiar with that?
This is to show that functions are first-class in Julia as in Python.
- There are a lot of functions going on here- can we link to some documentation?
OK.
- I think we will need to slim this part down a lot. Can we strip it back to an 'essential' core with documentation links to learn other things?
OK.
- Perhaps simplify things in the last cell- do we need to do nfold? Could it be included separately as an "Extension" cell?
OK.
- I suspect we will need some slides that talk about things like expressions vs. statements in Julia and maybe begin-end / let-in blocks (is there a difference between them?)
I'm not sure if there is a difference between expressions and statements in Julia. I suppose everything is treated as an expression given the metaprogramming capability of Julia. For `begin-end` and `let-end` blocks, the former does not create a local scope, while the latter does.

**Comment by dorchard** [comment]
I think we have handled all this now.
