### ISSUE TITLE
`@kwdef` not defined

### ISSUE THREAD

**Issue by dorchard** [Cambridge-ICCS/Summer-School-Julia-Tutorial#4]
I get an error evaluating this cell: https://github.com/Cambridge-ICCS/Summer-School-Julia-Tutorial/blob/322df1c50207471b3bb275919845099f74d9b9f3/pdist.jl#L35
with `@kwdef` not defined. Do we need so many macros for a intro session in any case?

**Comment by casterkay** [comment]
It's documented [here](https://docs.julialang.org/en/v1/base/base/#Base.@kwdef). Is your Julia version higher than 1.1?

**Comment by dorchard** [comment]
I'm on v1.8.5 but get:
```
UndefVarError: @kwdef not defined

top-level scope@:0
#macroexpand#61@expr.jl:115[inlined]
macroexpand@expr.jl:113[inlined]
try_macroexpand(::Module, ::Base.UUID, ::Expr)@PlutoRunner.jl:271
var"#run_expression#27"(::Bool, ::Bool, ::typeof(Main.PlutoRunner.run_expression), ::Module, ::Expr, ::Base.UUID, ::Base.UUID, ::Union{Nothing, Tuple{Set{Symbol}, Set{Symbol}}}, ::Union{Nothing, UInt64})@PlutoRunner.jl:514
top-level scope@none:1
```

**Comment by casterkay** [comment]
It's because before Julia 1.9, the macro is not export from `Base`, so it has to be used as `Base.@kwdef`. After that we can directly use `@kwdef`.

**Comment by dorchard** [comment]
Closing as we don't use this anymore it seems.
