### ISSUE TITLE
`ebm` will use `Symbolics` put some reference to this into the notebook

### ISSUE THREAD

**Issue by dorchard** [Cambridge-ICCS/Summer-School-Julia-Tutorial#7]
We need to at least mention what is going on with `Symbolics` and abstract syntax trees in `ebm` as we don't want to have `ebm` depend on `fibonacci` (which currently introduces Symbolics in more detail).  The `ebm` notebook can refernece `fibonacci` as a place to get more info on symbolics.

**Comment by casterkay** [comment]
Since we have removed `fibonacci` from the workshop, I think we would need to introduce `Symbolics` in `ebm` when we show the ODE system.
